table Orders
	lineageTag: 7552ac24-abbe-4ee4-90b9-4cde7e8413aa

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 2ac2bed2-89a0-4716-8292-c51ae0c53b5d
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 33a86856-1856-433b-8378-57e70dc2c455
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a7a77d68-512f-48b6-bdb9-0f812c74272c
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 68949008-1661-445f-b9a7-f9b97101b281
			defaultHierarchy: LocalDateTable_60edbaf6-de41-4cf3-a156-7653cb75d62b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8f02951-20e4-4779-a231-820cd546ceec
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 9791d1d2-2a95-4880-8d56-fe0142bdf24d
			defaultHierarchy: LocalDateTable_76d8368b-f020-45ea-bc2d-99f7d95c43ec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 9c55991a-d00c-43ee-8e07-9496d3691d3c
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: c0a650f6-2e70-463b-8bae-31ca18ff65a2
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: bbe802cc-648a-4092-8772-b2594932f349
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 259faf27-8eaf-4f4e-b72f-22e1849b31f5
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 4bf7c7cd-85e4-4f1a-9f31-3c891f2ee231
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 9c173158-6549-47b9-83eb-789255c22981
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: a25f2f01-681a-4e4f-8a87-eb7e1f9dbc8a
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 319a5812-7072-4758-9db4-6be7f9f4156e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 02f8c228-94ac-4fb1-9f11-74ef6b0d6470
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1625378b-1b6f-4420-9900-fa5855a0d2ae
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 651c0aa1-b62d-412f-9568-1c22188efc38
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 1032a119-0a56-44cb-9606-95724e67a8c1
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 80bea630-8b58-4206-981a-9ad7813ed324
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: c13245fd-e4ce-48de-902a-6d0ae9dc849c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 9a53740a-bbcf-4d1f-9129-cd6c06d1b86c
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 9d16412d-c804-4de8-9db4-872a00ce68a9
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\TRAINING-BI\Resources\Orders.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Customer Segment", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

