table People
	lineageTag: 9d1542a9-94a0-4fe0-a2bd-b65c313f7f32

	column Person
		dataType: string
		lineageTag: 024299fe-c617-4c7a-947b-f51bf1cc8d95
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: b380846b-df9d-4073-b6e4-f1147f07f15d
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition People = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\TRAINING-BI\Resources\People.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"State", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

